services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  test:
    build: .
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py test
      "
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Host 5433 → Container 5432 to avoid problems in case you have a postgresql running in your pc

volumes:
  postgres_data:
